### ISSUE TITLE
Cannot install other necessary tools downstream projects may need.

### ISSUE THREAD

**Issue by roosemberth** [fischerscode/DockerFlutter#15]
I'm trying to use this image to build my flutter app. Building my application requires `rsync`, but I cannot install it since the running user does not have the necessary permissions.

I think the image should include a way to escalate back to root (e.g. `sudo`) and authorize user `flutter` to do so.

**Comment by thekucays** [comment]
i encountered the same problem when try to install some additional packages needed for my project

`#5 4.078 E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
#5 4.078 E: Unable to lock directory /var/lib/apt/lists/`

**Comment by fischerscode** [comment]
Sorry @roosemberth I completely missed your comment.

I've created [fischerscode/flutter-sudo](https://hub.docker.com/r/fischerscode/flutter-sudo). It contains `sudo` and `flutter` is authorized to use it. (4926754fc6e06e5f4ff331f3c16444138a3fa7fd)

Please reopen the issue in case you encounter any problems.
