### ISSUE TITLE
Please upgrade the image to latest Flutter (v3.13.x)

### ISSUE THREAD

**Issue by KRTirtho** [fischerscode/DockerFlutter#39]
Currently the image is stuck at Flutter 3.10.x but Flutter 3.13.x was released & seeing the actions tab the builds are failing for some reason

**Comment by fischerscode** [comment]
Actions disabled themself due to repo inactivity. I've now reactivated them. All the missing versions should be available soon.

**Comment by KRTirtho** [comment]
Thanks a lot :+1: 
Is there any plan to support Ubuntu 22.04 LTS? Currently, currently Ubuntu 20.04 LTS is used which is old LTS and near it's end of lifetime

Also I noticed `$HOME/.pub-cache/bin` is not added in prior. It can be done manually but having it pre-configured is a nice touch. It just makes sure binaries like pub global package binaries are in PATH

**Comment by fischerscode** [comment]
@KRTirtho Sorry for the late response.
I've implemented your requests in a09bde8 and 3e46bf4. Currently, already build tags are not rebuild. I might have to come up with a solution for this.

**Comment by KRTirtho** [comment]
Thanks a lot. Keep on the good work :heart: :muscle:
