### ISSUE TITLE
The current Flutter SDK version is 0.0.0-unknown for `master` branch

### ISSUE THREAD

**Issue by Juneezee** [fischerscode/DockerFlutter#5]
The Flutter version of the `master` image is `0.0.0-unknown`. This is problematic as version solving will fail in `flutter pub get`.

EDIT: `flutter doctor` reports this as well. Here is one of the action log: https://github.com/fischerscode/DockerFlutter/runs/2769430981?check_suite_focus=true#step:5:239

EDIT 2: `master` image is not the only one. Other branches are having version `0.0.0-unknown` as well. The root cause seems to be the `--depth 1` flag here https://github.com/fischerscode/DockerFlutter/blob/74b19556a91a290567a13d38d149e53480daba6e/Dockerfile#L17

**Comment by fischerscode** [comment]
@Juneezee 
The current active branches have rebuild now, and your PR fixed the issue. (I run `flutter doctor` in the new master tag).
I'll try to find a way to scan the existing tags and rebuild them if needed.
Thanks again for your contribution.

**Comment by fischerscode** [comment]
There is now a [workflow](https://github.com/fischerscode/DockerFlutter/actions/workflows/scan_images.yaml) scanning for invalid builds.

**Comment by zs-dima** [comment]
@fischerscode this issue still exists in all the latest `fischerscode/flutter-sudo`
